export default {
    collectionName: "tenant_entity",
    title: "Tenant Entities",
    fields: [
        {
            label: "Entity Name",
            key: "name",
            type: "text",
            rank: 0,
        },
        {
            label: "Database Name",
            key: "db_name",
            type: "text",
            rank: 1,
        },
        {
            label: "Street address",
            key: "street",
            type: "text",
            rank: 2,
        },
        {
            label: "Zip Code",
            key: "zip",
            type: "text",
            rank: 3,
        },
        {
            label: "City",
            key: "city",
            type: "text",
            rank: 4,
        },
        {
            label: "State/Province",
            key: "state",
            type: "text",
            rank: 5,
        },
        {
            label: "Country",
            key: "country",
            type: "text",
            rank: 6,
        },
        {
            label: "Active",
            key: "active",
            type: "boolean",
            defaultValue: true,
            rank: 7,
        },
        {
            key: "notes",
            label: "Notes",
            type: "textarea",
            rows: 5,
            rank: 8,
            display: true,
            displayInTable: false,
        },
        {
            key: "created_at",
            label: "Created at",
            type: "date",
            readOnly: true,
            rank: 9,
            display: true,
            export: false,
        },
        {
            label: "Updated at",
            key: "updated_at",
            type: "date",
            readOnly: true,
            rank: 10,
            display: true,
        },
    ],
};